
local CORNER_LEFT_TOP = "leftCornerTop"
local CORNER_RIGHT_TOP = "rightCornerTop"
local CORNER_LEFT_TOP_ROUNDED = "leftCornerTopRounded"
local CORNER_RIGHT_TOP_ROUNDED = "rightCornerTopRounded"
local CORNER_LEFT_BOTTOM = "leftCornerBottom"
local CORNER_RIGHT_BOTTOM = "rightCornerBottom"
local CORNER_LEFT_BOTTOM_ROUNDED = "leftCornerBottomRounded"
local CORNER_RIGHT_BOTTOM_ROUNDED = "rightCornerBottomRounded"
local SIDE = "side"
local SIDE_BOTTOM = "sideBottom"
local SPLIT_TOP = "split_top"
local SPLIT_BOTTOM = "splitBottom"
local SPLIT_LEFT_SIDE = "splitLeftSide"
local SPLIT_RIGHT_SIDE = "splitRightSide"
local SPLIT_MIDLE = "splitMidle"

return {
  CORNER_LEFT_TOP =  CORNER_LEFT_TOP ,
  CORNER_RIGHT_TOP =  CORNER_RIGHT_TOP ,
  CORNER_LEFT_TOP_ROUNDED =  CORNER_LEFT_TOP_ROUNDED ,
  CORNER_RIGHT_TOP_ROUNDED =  CORNER_RIGHT_TOP_ROUNDED ,
  CORNER_LEFT_BOTTOM =  CORNER_LEFT_BOTTOM ,
  CORNER_RIGHT_BOTTOM =  CORNER_RIGHT_BOTTOM ,
  CORNER_LEFT_BOTTOM_ROUNDED =  CORNER_LEFT_BOTTOM_ROUNDED ,
  CORNER_RIGHT_BOTTOM_ROUNDED =  CORNER_RIGHT_BOTTOM_ROUNDED ,
  SIDE =  SIDE ,
  SIDE_BOTTOM =  SIDE_BOTTOM ,
  SPLIT_TOP =  SPLIT_TOP ,
  SPLIT_BOTTOM =  SPLIT_BOTTOM ,
  SPLIT_LEFT_SIDE =  SPLIT_LEFT_SIDE ,
  SPLIT_RIGHT_SIDE =  SPLIT_RIGHT_SIDE ,
  SPLIT_MIDLE =  SPLIT_MIDLE,
}
